# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 18:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adoptApetApp', '0002_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='user_name',
        ),
        migrations.AddField(
            model_name='pet',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
