# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptApetApp', '0003_auto_20170102_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.FileField(upload_to='media/%Y/%m/%d'),
        ),
    ]
