# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptApetApp', '0005_auto_20170102_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='description',
            field=models.CharField(default='No Description', max_length=550),
        ),
    ]
