# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoptApetApp', '0006_pet_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='description',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
